version: '3.7'

networks:
  reverse-proxy:
    external: true

services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    networks:
      - reverse-proxy
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
  frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-front
    hostname: registry-front
    restart: unless-stopped
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    networks:
      - reverse-proxy
