version: '3.7'

networks:
  reverse-proxy:
    external: true

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    hostname: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    deploy:
      resources: 
        limits: 
          cpus: '0.9'
          memory: '512M'
    networks:
      - reverse-proxy
    volumes:      
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
