version: '3.7'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8080:8080
    hostname: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/ssl/certs:/etc/ssl/certs
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '512M'
#  agent:
#    container_name: jenkins-agent
#    image: jenkins/ssh-agent:alpine-jdk17
#    restart: unless-stopped
#    privileged: true
#    user: root
#    env_file:
#      - .env
